### ISSUE TITLE
Refresh breaks demo on Chrome 4 with AdThwart extension

### ISSUE THREAD

**Issue by chuchuva** [cowboy/jquery-hashchange#3] opened 2010-04-06 06:47 UTC
Chrome 4.0.249.43 with AdThwart 0.8.12,  Windows XP
Repro:
- Open http://benalman.com/code/projects/jquery-hashchange/examples/hashchange/ 
- Click refresh button

Observe: links loose CSS styling
Expected: links remain the same

**Comment by cowboy** [comment] 2010-04-06 14:09
I can't reproduce this issue in Windows XP or 7 in Chrome 4 or 5.

Can you open the site in incognito mode, without extensions? You might have a conflicting extension or user script installed.

**Comment by chuchuva** [comment] 2010-04-06 23:18
You are right, it only happens with AdThwart extension. AdThwart version is 0.8.12

**Comment by cowboy** [comment] 2010-04-06 23:29
Ok, I'm closing this issue then, since there's nothing I can do about that extension.

**Closed as completed by cowboy** 2010-04-06 23:29 UTC
